name: 'Test AiiDA lab app'
description: "Test an AiiDA lab app."
inputs:
  image:
    description: 'The aiidalab docker image to test on.'
    default: 'aiidalab/aiidalab-docker-stack:latest'
  browser:
    description: 'Which browser to execute tests for.'
    default: 'chrome'
runs:
  using: 'node12'
  main: 'index.js'
  post: 'cleanup.js'
