# Build and push the selenium container neded for test execution.
name: "build-selenium-container"

on:
  [push]

jobs:
  build-docker-image:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: build image
        uses: docker/build-push-action@v1
        with:
          path: selenium-tests
          repository: aiidalab/aiidalab-test-app-action
          tags: selenium-tests
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
